set shell := ["bash", "-uc"]

# List the available commands
help:
    @just --list --justfile {{justfile()}}

# Prepare the environment for development, installing all the dependencies and
# setting up the pre-commit hooks.
setup:
    uv sync
    [[ -n "${JUST_INHIBIT_GIT_HOOKS:-}" ]] || uv run pre-commit install -t pre-commit

# Run the pre-commit checks.
check:
    uv run pre-commit run --all-files


# Run the tests.
test *PYTEST_FLAGS:
    uv run pytest -n auto {{PYTEST_FLAGS}}

# Export the integration test cases to a directory.
export-integration-tests directory="guppy-exports":
    uv run pytest -n auto --export-test-cases="{{ directory }}"

# test-exported-hugrs *PYTEST_FLAGS: export-integration-tests
test-exported-hugrs *PYTEST_FLAGS:
    uv run pytest -n auto -m test_exported_hugrs {{PYTEST_FLAGS}}

# Auto-fix all clippy warnings.
fix:
    uv run ruff check --fix

# Format the code.
format:
    uv run ruff format

# Generate a test coverage report.
coverage:
    uv run pytest --cov=./ --cov-report=html

# Generate the documentation.
build-docs:
    cd docs && ./build.sh

# Serve sphinx docs locally (needs npm installed)
serve-docs: build-docs
    npm exec serve docs/build/api-docs

# Remove files generated by the sphinx build
clean-docs:
    rm -rf docs/build
    rm -rf docs/api-docs/generated

# Package the code and store the wheels in the dist/ directory.
build-wheels:
    uvx --from build pyproject-build --installer uv


NOW := `date +%s%n | tr -d '\n'`
BENCHER_PROJECT := "guppylang-benchmarks"

# Run benchmarks and upload the results using bencher_cli. Note: Needs the BENCHER_API_TOKEN env variable.
bench_upload *BENCHER_FLAGS:
    uv run pytest \
           --override-ini addopts="" \
           --benchmark-only \
           --benchmark-quiet \
           --benchmark-json="{{NOW}}-pytest-benchmark.json" \
           -k "compile"
    uv run python tests/bencher.py "{{NOW}}-pytest-benchmark.json" "{{NOW}}-bencher.json"
    bencher run \
            --file "{{NOW}}-bencher.json" \
            --adapter json \
            --project {{BENCHER_PROJECT}} \
            --quiet \
            {{BENCHER_FLAGS}}

# Run benchmarks and compare the results using bencher_cli. Note: Needs the BENCHER_API_TOKEN env variable.
bench-compare *BENCHER_FLAGS:
    uv run pytest \
           --override-ini addopts="" \
           --benchmark-only \
           --benchmark-quiet \
           --benchmark-json="{{NOW}}-pytest-benchmark.json" \
           -k "compile"
    uv run python tests/bencher.py "{{NOW}}-pytest-benchmark.json" "{{NOW}}-bencher.json"
    bencher run \
            --project {{BENCHER_PROJECT}} \
            --adapter json \
            --file "{{NOW}}-bencher.json" \
            --average median \
            --threshold-measure hugr_bytes \
            --threshold-test percentage \
            --threshold-upper-boundary 0.01 \
            --threshold-measure hugr_nodes \
            --threshold-test percentage \
            --threshold-upper-boundary 0.01 \
            --err \
            --quiet \
            {{BENCHER_FLAGS}}
