name: Benchmark main

on:
  push:
    branches: main

env:
  UV_VERSION: "0.9.5"

permissions:
  contents: read
  id-token: write # required for OIDC auth with Codspeed

jobs:
  benchmark_base_branch:
    name: Continuous Benchmarking
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true

      - name: Set up bencher
        uses: bencherdev/bencher@main

      - name: Set up Just
        uses: extractions/setup-just@v4

      - name: Benchmark main with Bencher
        run: |
          just bench-upload \
               --token '${{ secrets.BENCHER_API_TOKEN }}' \
               --testbed Linux \
               --branch main \
               --github-actions '${{ secrets.GITHUB_TOKEN }}' \

      - name: Benchmark main with CodSpeed
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: uv run pytest tests/ --codspeed -k "not executable"
