name: Check Conventional Commits format
on:
  pull_request_target:
    branches:
      - main
      # Also run on the 0.21.x series. This has to be configured on the main
      # branch since we are using `pull_request_target`, which runs in that
      # context.
      - guppylang-0.21
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
  merge_group:
    types: [checks_requested]

jobs:
    check-title:
        name: check-title
        uses: quantinuum/hugrverse-actions/.github/workflows/pr-title.yml@main
        secrets:
            GITHUB_PAT: ${{ secrets.HUGRBOT_PAT }}
